// Mapeo de imágenes por ID de producto (no cambia aunque cambien los nombres)
const productos = [
  { id: 17, name: 'AREPA TIPO OBLEA', image: require('../images/arepa-tipo-oblea-500g.jpeg') },
  { id: 18, name: 'AREPA MEDIANA', image: require('../images/Arepa-de-Maíz-Peto-Mediana.jpeg') },
  { id: 21, name: 'AREPA TIPO PINCHO', image: require('../images/arepa-tipo-pincho.jpeg') },
  { id: 22, name: 'AREPA QUESO 450 G', image: require('../images/arepa-con-queso corrente.jpeg') },
  { id: 23, name: 'AREPA QUESO ESP/GRANDE', image: require('../images/arepa-conqueso-especial-grande.jpeg') },
  { id: 24, name: 'AREPA QUESO ESP/PEQUEÑA', image: require('../images/arepa-con-queso-especial-pequeña.jpeg') },
  { id: 25, name: 'AREPA QUESO MINI X10', image: require('../images/arepa-con-queso-mini-x10.jpeg') },
  { id: 26, name: 'AREPA CON QUESO CUADRADA X5 UND', image: require('../images/arepa-con-queso-cuadrada.jpeg') },
  { id: 27, name: 'AREPA CHOCLO 300Gr', image: require('../images/arepa-de-choclo-corriente.jpeg') },
  { id: 28, name: 'AREPA CHOCLO QUESO GRANDE', image: require('../images/arepa-de-choclo-con-queso-grande.jpeg') },
  { id: 29, name: 'AREPA CHOCLO QUESO PEQUEÑA', image: require('../images/arepa-choclo-con-queso-pequeña.jpeg') },
  { id: 30, name: 'AREPA DE CHOCLO CON QUESO PEQUEÑA 700 Gr', image: require('../images/arepa-choclo-con-queso-pequeña.jpeg') },
  { id: 31, name: 'AREPA BOYACENSE UND', image: require('../images/arepa-boyacense-x-5.jpeg') },
  { id: 32, name: 'AREPA BOYACENSE X 10', image: require('../images/arepa-boyacense-x-5.jpeg') },
  { id: 33, name: 'AREPA SANTANDEREANA', image: require('../images/arepa-santanderana.jpeg') },
  { id: 34, name: 'ALMOJABANA UND', image: require('../images/almojabanas-x-5.jpeg') },
  { id: 35, name: 'ALMOJABANAS X 10 600Gr', image: require('../images/almojabanas-x-5.jpeg') },
  { id: 36, name: 'AREPA CON SEMILLAS DE QUINUA', image: require('../images/arepa-semilla-quinua.jpeg') },
  { id: 37, name: 'AREPA CON SEMILLAS DE CHIA', image: require('../images/arepa-semilla-chia.jpeg') },
  { id: 38, name: 'AREPA CON SEMILLAS DE AJONJOLI', image: require('../images/arepa-semilla-ajonjoli.jpeg') },
  { id: 39, name: 'AREPA CON SEMILLAS DE LINAZA', image: require('../images/arepa-semilla-linaza.jpeg') },
  { id: 40, name: 'AREPA CON SEMILLAS DE GIRASOL', image: require('../images/arepa-semilla-girasol.jpeg') },
  { id: 41, name: 'AREPA CHORICERA', image: require('../images/arepa-choricera.jpeg') },
  { id: 42, name: 'AREPA LONCHERIA X10 UND', image: require('../images/arepa-loncheria.jpeg') },
  { id: 43, name: 'AREPA CON MARGARINA Y SAL', image: require('../images/arepa-margarina-sal.jpeg') },
  { id: 44, name: 'YUCAREPA', image: require('../images/yucarepa.png') },
  { id: 45, name: 'AREPA TIPO ASADERO X10 UND', image: require('../images/arepa-asadero.jpeg') },
  { id: 46, name: 'AREPA PARA RELLENAR #1', image: require('../images/arepa-rellenar-1-2.jpeg') },
  { id: 47, name: 'AREPA PARA RELLENA #2', image: require('../images/arepa-rellenar-1-2.jpeg') },
  { id: 48, name: 'AREPA PARA RELLENAR #3', image: require('../images/arepa-para-rellenar.jpeg') },
  { id: 49, name: 'PORCIÓN DE AREPAS X2', image: require('../images/arepa-porcion-x2.jpeg') },
  { id: 50, name: 'PORCIÓN DE AREPAS X3', image: require('../images/arepa-porcionx4.jpeg') },
  { id: 51, name: 'PORCIÓN DE AREPAS X4', image: require('../images/arepa-porcionx4.jpeg') },
  { id: 52, name: 'PORCIÓN DE AREPAS X5', image: require('../images/arepa-porcionx4.jpeg') },
  { id: 53, name: 'AREPA SUPER OBLEA', image: require('../images/arepa-superoblea.jpeg') },
  { id: 54, name: 'LIBRA MASA', image: require('../images/masa.jpeg') },
  { id: 55, name: 'MUTE BOYACENSE XLB', image: require('../images/maiz-peto.jpeg') },
  { id: 56, name: 'ENVUELTOS DE MAIZ X 5 UND', image: require('../images/envueltos.jpeg') },
];

export default productos;
