const productos = [
  { name: 'AREPA TIPO OBLEA 500Gr', image: require('../images/Arepa-De-Maiz-Peto-Tipo-Oblea-500g.jpeg') },
  { name: 'AREPA MEDIANA 330Gr', image: require('../images/Arepa-de-Maíz-Peto-Mediana.jpeg') },
  { name: 'AREPA TIPO PINCHO 330Gr', image: require('../images/arepa-tipo-pincho.jpeg') },
  { name: 'AREPA QUESO CORRIENTE 450Gr', image: require('../images/arepa-con-queso corrente.jpeg') },
  { name: 'AREPA QUESO ESPECIAL GRANDE 600Gr', image: require('../images/arepa-conqueso-especial-grande.jpeg') },
  { name: 'AREPA CON QUESO ESPECIAL PEQUEÑA 600Gr', image: require('../images/arepa-con-queso-especial-pequeña.jpeg') },
  { name: 'AREPA QUESO MINI X10', image: require('../images/arepa-con-queso-mini-x10.jpeg') },
  { name: 'AREPA CON QUESO CUADRADA 450Gr', image: require('../images/arepa-con-queso-cuadrada.jpeg') },
  { name: 'AREPA DE CHOCLO CORRIENTE 300Gr', image: require('../images/arepa-de-choclo-corriente.jpeg') },
  { name: 'AREPA DE CHOCLO CON QUESO GRANDE 1200Gr', image: require('../images/arepa-de-choclo-con-queso-grande.jpeg') },
  { name: 'AREPA DE CHOCLO CON QUESO PEQUEÑA 700Gr', image: require('../images/arepa-choclo-con-queso-pequeña.jpeg') },
  { name: 'AREPA BOYACENSE X 5 450Gr', image: require('../images/arepa-boyacense-x-5.jpeg') },
  { name: 'AREPA SANTANDEREANA 450Gr', image: require('../images/arepa-santanderana.jpeg') },
  { name: 'ALMOJABANA X 5 300Gr', image: require('../images/almojabanas-x-5.jpeg') },
  { name: 'AREPA CON SEMILLA DE QUINUA 450Gr', image: require('../images/arepa-semilla-quinua.jpeg') },
  { name: 'AREPA DE MAIZ CON SEMILLA DE CHIA450Gr', image: require('../images/arepa-semilla-chia.jpeg') },
  { name: 'AREPAS DE MAIZ PETO CON SEMILLA DE AJONJOLI 450GR', image: require('../images/arepa-semilla-ajonjoli.jpeg') },
  { name: 'AREPA DE MAIZ PETO CON SEMILLAS DE LINAZA 450Gr', image: require('../images/arepa-semilla-linaza.jpeg') },
  { name: 'AREPA DE MAIZ PETO CON SEMILLAS DE GIRASOL 450Gr', image: require('../images/arepa-semilla-girasol.jpeg') },
  { name: 'AREPA DE MAIZ PETO CHORICERA 1000Gr', image: require('../images/arepa-choricera.jpeg') },
  { name: 'AREPA DE MAIZ DE PETO TIPO LONCHERIA 500Gr', image: require('../images/arepa-loncheria.jpeg') },
  { name: 'AREPA DE MAIZ PETO CON MARGARINA Y SAL 500Gr', image: require('../images/arepa-margarina-sal.jpeg') },
  { name: 'YUCAREPA 500Gr', image: require('../images/yucarepa.png') },
  { name: 'AREPA TIPO ASADERO X 10 280Gr', image: require('../images/arepa-asadero.jpeg') },
  { name: 'AREPA RELLENAR #1', image: require('../images/arepa-rellenar-1-2.jpeg') },
  { name: 'AREPA PARA RELLENA #2', image: require('../images/arepa-rellenar-1-2.jpeg') },
  { name: 'AREPA RELLENAR #3 1000Gr', image: require('../images/arepa-para-rellenar.jpeg') },
  { name: 'PORCION DE AREPA X 2 UND 55Gr', image: require('../images/arepa-porcion-x2.jpeg') },
  { name: 'PORCION DE AREPA 3 UND', image: require('../images/arepa-porcionx4.jpeg') },
  { name: 'PORCION DE AREPA 4 UND 110 GR', image: require('../images/arepa-porcionx4.jpeg') },
  { name: 'PORCION DE AREPA 5 UND', image: require('../images/arepa-porcionx4.jpeg') },
  { name: 'AREPA SUPER OBLEA 500Gr', image: require('../images/arepa-superoblea.jpeg') },
  { name: 'LIBRA MASA', image: require('../images/masa.jpeg') },
  { name: 'MUTE BOYACENSE', image: require('../images/maiz-peto.jpeg') },
  { name: 'ENVUELTO DE MAÍZ 500Gr', image: require('../images/envueltos.jpeg') },
  { name: 'CANASTILLA', image: require('../images/canasta.png') },
];

export default productos;
